import React, { useState, useEffect } from 'react';
import { Shield, Zap, Target, TrendingUp, Globe, Search } from 'lucide-react';

const MainApp: React.FC = () => {
  const [apiKey, setApiKey] = useState('');
  const [provider, setProvider] = useState<'openai' | 'anthropic' | 'google'>('openai');
  const [topic, setTopic] = useState('');
  const [location, setLocation] = useState('');
  const [generating, setGenerating] = useState(false);
  const [content, setContent] = useState('');
  const [progress, setProgress] = useState(0);

  const handleGenerate = async () => {
    if (!apiKey || !topic || !location) {
      alert('Please fill in all required fields');
      return;
    }

    setGenerating(true);
    setProgress(0);
    setContent('');

    try {
      // Simulate progress for demo
      const progressInterval = setInterval(() => {
        setProgress(prev => {
          if (prev >= 95) {
            clearInterval(progressInterval);
            return 95;
          }
          return prev + 5;
        });
      }, 200);

      // Generate content with selected provider
      const response = await generateContent({
        provider,
        apiKey,
        topic,
        location
      });

      clearInterval(progressInterval);
      setProgress(100);
      setContent(response);
    } catch (error) {
      console.error('Generation error:', error);
      alert('Failed to generate content. Please check your API key and try again.');
    } finally {
      setGenerating(false);
    }
  };

  const generateContent = async (params: any): Promise<string> => {
    // Mock implementation for demo - replace with actual API calls
    await new Promise(resolve => setTimeout(resolve, 3000));
    
    return `# ${params.topic} in ${params.location}

## Introduction

Welcome to the ultimate guide about ${params.topic} in ${params.location}. This comprehensive article has been optimized for maximum SEO performance using state-of-the-art AI technology.

## Why ${params.topic} Matters in ${params.location}

${params.topic} has become increasingly important in ${params.location} due to several key factors:

- Local market demand and trends
- Community needs and preferences
- Regional economic conditions
- Cultural significance

## Key Benefits

1. **Enhanced Visibility**: Optimized content that ranks higher in search results
2. **Targeted Traffic**: Attracts the right audience from ${params.location}
3. **Conversion Optimization**: Content designed to convert visitors into customers
4. **Authority Building**: Establishes your brand as a local expert

## Best Practices

To maximize success with ${params.topic} in ${params.location}, consider these proven strategies:

### Strategy 1: Local SEO Optimization
Focus on location-specific keywords and phrases that resonate with your ${params.location} audience.

### Strategy 2: Quality Content
Provide valuable, actionable information that addresses local needs and questions.

### Strategy 3: User Experience
Ensure your content is easy to read, well-structured, and mobile-friendly.

## Conclusion

${params.topic} presents unique opportunities in ${params.location}. By following the strategies outlined in this guide, you can create compelling content that drives results.

---

*Generated by Ultra-SOTA WP Content Generator - Optimized for maximum SEO performance*`;
  };

  return (
    <div className="min-h-screen py-12 px-4">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="text-center mb-12">
          <h1 className="text-5xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-purple-400 via-pink-500 to-purple-600 mb-4">
            Ultra-SOTA Content Generator
          </h1>
          <p className="text-xl text-gray-300">
            AI-Powered WordPress Content with Advanced SEO Optimization
          </p>
        </div>

        {/* Stats */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-12">
          <StatCard icon={<Zap />} label="Lightning Fast" value="2-3 sec" color="purple" />
          <StatCard icon={<Target />} label="SEO Score" value="95+" color="pink" />
          <StatCard icon={<TrendingUp />} label="Quality Rating" value="AAA+" color="purple" />
        </div>

        {/* Main Content Area */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Input Panel */}
          <div className="bg-white/10 backdrop-blur-lg rounded-2xl p-8 border border-white/20 shadow-2xl">
            <h2 className="text-2xl font-bold text-white mb-6 flex items-center gap-3">
              <Shield className="w-6 h-6 text-purple-400" />
              Configuration
            </h2>

            <div className="space-y-6">
              {/* Provider Selection */}
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">
                  AI Provider
                </label>
                <select
                  value={provider}
                  onChange={(e) => setProvider(e.target.value as any)}
                  className="w-full px-4 py-3 bg-black/30 border border-white/20 rounded-xl text-white focus:outline-none focus:ring-2 focus:ring-purple-500 transition-all"
                >
                  <option value="openai">OpenAI GPT-4</option>
                  <option value="anthropic">Anthropic Claude</option>
                  <option value="google">Google Gemini</option>
                </select>
              </div>

              {/* API Key */}
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">
                  API Key
                </label>
                <input
                  type="password"
                  value={apiKey}
                  onChange={(e) => setApiKey(e.target.value)}
                  placeholder="Enter your API key"
                  className="w-full px-4 py-3 bg-black/30 border border-white/20 rounded-xl text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-purple-500 transition-all"
                />
              </div>

              {/* Topic */}
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2 flex items-center gap-2">
                  <Search className="w-4 h-4" />
                  Topic/Keyword
                </label>
                <input
                  type="text"
                  value={topic}
                  onChange={(e) => setTopic(e.target.value)}
                  placeholder="e.g., Best Coffee Shops"
                  className="w-full px-4 py-3 bg-black/30 border border-white/20 rounded-xl text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-purple-500 transition-all"
                />
              </div>

              {/* Location */}
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2 flex items-center gap-2">
                  <Globe className="w-4 h-4" />
                  Location
                </label>
                <input
                  type="text"
                  value={location}
                  onChange={(e) => setLocation(e.target.value)}
                  placeholder="e.g., New York City"
                  className="w-full px-4 py-3 bg-black/30 border border-white/20 rounded-xl text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-purple-500 transition-all"
                />
              </div>

              {/* Generate Button */}
              <button
                onClick={handleGenerate}
                disabled={generating}
                className="w-full px-8 py-4 bg-gradient-to-r from-purple-600 to-pink-600 text-white font-bold rounded-xl hover:scale-105 transform transition-all duration-300 shadow-lg hover:shadow-purple-500/50 disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100"
              >
                {generating ? (
                  <span className="flex items-center justify-center gap-2">
                    <div className="w-5 h-5 border-3 border-white/30 border-t-white rounded-full animate-spin"></div>
                    Generating... {progress}%
                  </span>
                ) : (
                  'Generate Content'
                )}
              </button>
            </div>
          </div>

          {/* Output Panel */}
          <div className="bg-white/10 backdrop-blur-lg rounded-2xl p-8 border border-white/20 shadow-2xl">
            <h2 className="text-2xl font-bold text-white mb-6 flex items-center gap-3">
              <TrendingUp className="w-6 h-6 text-pink-400" />
              Generated Content
            </h2>

            {content ? (
              <div className="space-y-4">
                <div className="max-h-[600px] overflow-y-auto bg-black/30 rounded-xl p-6 border border-white/10">
                  <pre className="whitespace-pre-wrap text-gray-300 text-sm font-mono">
                    {content}
                  </pre>
                </div>
                <button
                  onClick={() => navigator.clipboard.writeText(content)}
                  className="w-full px-6 py-3 bg-gradient-to-r from-green-600 to-emerald-600 text-white font-semibold rounded-xl hover:scale-105 transform transition-all duration-300 shadow-lg"
                >
                  Copy to Clipboard
                </button>
              </div>
            ) : (
              <div className="h-[600px] flex items-center justify-center border-2 border-dashed border-white/20 rounded-xl">
                <div className="text-center text-gray-400">
                  <div className="text-6xl mb-4">📝</div>
                  <p className="text-lg">Your generated content will appear here</p>
                  <p className="text-sm mt-2">Configure settings and click Generate</p>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* Features */}
        <div className="mt-12 grid grid-cols-1 md:grid-cols-3 gap-6">
          <FeatureCard
            title="SEO Optimized"
            description="Content automatically optimized for search engines with proper keywords, headings, and structure."
            icon="🎯"
          />
          <FeatureCard
            title="Location-Based"
            description="Geo-targeted content that resonates with local audiences and ranks for location-specific searches."
            icon="📍"
          />
          <FeatureCard
            title="AI-Powered"
            description="Leveraging cutting-edge AI models for human-quality content that engages and converts."
            icon="🤖"
          />
        </div>
      </div>
    </div>
  );
};

const StatCard: React.FC<{ icon: React.ReactNode; label: string; value: string; color: string }> = ({ icon, label, value, color }) => (
  <div className={`bg-white/10 backdrop-blur-lg rounded-xl p-6 border border-white/20 hover:scale-105 transform transition-all duration-300`}>
    <div className={`text-${color}-400 mb-3`}>{icon}</div>
    <div className="text-3xl font-bold text-white mb-1">{value}</div>
    <div className="text-gray-300 text-sm">{label}</div>
  </div>
);

const FeatureCard: React.FC<{ title: string; description: string; icon: string }> = ({ title, description, icon }) => (
  <div className="bg-white/10 backdrop-blur-lg rounded-xl p-6 border border-white/20 hover:scale-105 transform transition-all duration-300">
    <div className="text-4xl mb-4">{icon}</div>
    <h3 className="text-xl font-bold text-white mb-2">{title}</h3>
    <p className="text-gray-300 text-sm">{description}</p>
  </div>
);

export default MainApp;